# Generated by Django 4.2.7 on 2025-05-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournois", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("ordre", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Catégorie FAQ",
                "verbose_name_plural": "Catégories FAQ",
                "db_table": "categorie_faq",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("reponse", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("est_active", models.BooleanField(default=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        db_column="categorie_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="tournois.categoriefaq",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "db_table": "faq",
                "ordering": ["categorie", "question"],
            },
        ),
    ]
