# Generated by Django 4.2.7 on 2025-05-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0002_categoriefaq_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='supabase_uid',
            field=models.CharField(blank=True, help_text='Supabase User ID', max_length=255, null=True, unique=True),
        ),
    ]
