# Generated by Django 4.2.7 on 2025-05-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0003_utilisateur_supabase_uid'),
        ('tournois', 'create_admin_user'),
    ]

    operations = [
    ]
