# Generated by Django 4.2.7 on 2025-05-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0004_merge_0003_utilisateur_supabase_uid_create_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionTournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu', models.CharField(max_length=100)),
                ('pseudo', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('experience', models.TextField()),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournois.equipe')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournois.joueur')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournois.tournoi')),
            ],
            options={
                'verbose_name': 'Inscription au tournoi',
                'verbose_name_plural': 'Inscriptions aux tournois',
                'db_table': 'inscription_tournoi',
                'unique_together': {('tournoi', 'joueur')},
            },
        ),
    ]
