# Generated by Django 4.2.7 on 2025-05-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0005_inscriptiontournoi'),
    ]

    operations = [
    ]
