# Generated by Django 4.2.7 on 2025-05-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0006_auto_20250524_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrateur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='arbitre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='joueur',
            options={'ordering': ['-classement']},
        ),
        migrations.AlterModelOptions(
            name='organisateur',
            options={},
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='arbitre',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='classement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='niveau',
            field=models.CharField(default='débutant', max_length=50),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='nom_organisation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
